# source will be downloaded prior to filling in jinja templates
# Example assumes that this folder has setup.py in it
source:
  git_url: ../

package:
  name: dmf_device_ui_plugin
{% if GIT_DESCRIBE_NUMBER > '0' %}
  version: {{ GIT_DESCRIBE_TAG[1:] }}.post{{ GIT_DESCRIBE_NUMBER }}
{% else %}
  version: {{ GIT_DESCRIBE_TAG[1:] }}
{% endif %}

build:
  number: 0
  script: python -m mpm.bin.build

requirements:
  build:
    - dmf-device-ui >=0.2.post109
    - microdrop-plugin-manager >=0.10
    - pandas
    - path_helpers >=0.2.post3
    - pyyaml
    - si-prefix >=0.4.post10
    - wheeler.pygtkhelpers >=0.13.post17

  run:
    - dmf-device-ui >=0.2.post109
    - microdrop-plugin-manager >=0.10
    - pandas
    - path_helpers >=0.2.post3
    - pyyaml
    - si-prefix >=0.4.post10
    - wheeler.pygtkhelpers >=0.13.post17

about:
  home: http://github.com/wheeler-microfluidics/dmf_device_ui_plugin
  license: BSD
